services:
  db:
    image: supabase/postgres:15.1.0.118
    ports:
      - "5432:5432"
    volumes:
      # This uses a named volume instead of a bind mount
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=your_local_postgres_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env.local
    depends_on:
      - backend
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules

# This defines the named volume used by the db service
volumes:
  postgres_data: