name: Codex Fix
description: Ask Codex to implement a small, test-backed fix
labels: ["codex:fix"]
body:

  - type: textarea
    id: bug
    attributes: { label: Bug/Gap, description: "What's broken" }
    validations: { required: true }

  - type: textarea
    id: minimal
    attributes: { label: Minimal Fix, description: "What to change, where" }
    validations: { required: true }

  - type: textarea
    id: tests
    attributes: { label: Tests, description: "What to add/update" }
    validations: { required: true }

  - type: textarea
    id: acceptance
    attributes: { label: Acceptance, description: "Commands & green signals" }
    validations: { required: true }
