name: ci:auth-orders
on:
  pull_request:
    branches: [ main, master ]
    paths:
      - "server/**"
      - "shared/**"
      - ".github/workflows/ci-auth-orders.yml"
      - "package.json"
      - "scripts/**"

jobs:
  auth_orders:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Scoped typecheck & tests
        run: npm run ci:auth-orders