name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install dependencies
        run: npm ci
        
      - name: Install server dependencies
        run: cd server && npm ci
        
      - name: Install client dependencies
        run: cd client && npm ci
        
      - name: Verify no forbidden ports
        run: npm run verify:ports
        
      - name: Run ESLint
        run: npm run lint:fix -- --max-warnings=0
        
      - name: Type check
        run: npm run typecheck
        
      - name: Run tests
        run: npm test -- --runInBand
        env:
          NODE_ENV: test
          
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
        
      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true
        
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30