name: frontend-ci
on:
  pull_request:
    paths:
      - 'client/**'
      - '.github/workflows/frontend-ci.yml'
jobs:
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
      
      - name: TypeScript Check
        run: npm run typecheck
      
      - name: ESLint Check
        run: npm run lint
      
      - name: Run Cart Context Tests
        run: npm test -- src/modules/order-system/context/CartContext.test.tsx --runInBand --ci
      
      - name: Run Checkout E2E Tests
        run: npm test -- src/modules/order-system/__tests__/checkout.e2e.test.tsx --runInBand --ci
      
      - name: Build Production Bundle
        run: npm run build
        env:
          CI: true