name: frontend-ci
on:
  pull_request:
    paths:
      - 'client/**'
      - 'shared/**'
      - 'package.json'
      - 'tools/**'
      - 'scripts/**'
      - '.github/workflows/frontend-ci.yml'
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - 'scripts/docs-check.js'
      - 'scripts/reality-audit.sh'
      - '.github/workflows/docs-ci.yml'
      - '.github/workflows/docs-check.yml'
      - '.github/workflows/reality-audit.yml'

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        id: changed
        with:
          filters: |
            docs:
              - 'docs/**'
              - '**/*.md'
              - 'scripts/docs-check.js'
              - '.github/workflows/docs-ci.yml'
              - '.github/workflows/docs-check.yml'

      - name: Docs-only — short circuit
        if: ${{ steps.changed.outputs.docs == 'true' }}
        run: |
          echo "Docs-only PR detected; short-circuiting job with success."
          exit 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      
      - name: Install all dependencies
        run: npm ci
      
      - name: Guard - no compiled JS in shared
        run: npm run check:no-shared-js
      
      - name: Build Production Bundle
        run: cd client && npm run build
        env:
          CI: true
      
      - name: E2E Puppeteer
        run: node scripts/puppeteer-test.mjs
        env:
          CI: true
