name: Playwright Smoke Tests

on:
  pull_request:
    paths:
      - 'client/**'
      - '.github/workflows/playwright-smoke.yml'

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        id: changed
        with:
          filters: |
            docs:
              - 'docs/**'
              - '**/*.md'
              - 'scripts/docs-check.js'
              - '.github/workflows/docs-ci.yml'
              - '.github/workflows/docs-check.yml'

      - name: Docs-only — short circuit
        if: ${{ steps.changed.outputs.docs == 'true' }}
        run: |
          echo "Docs-only PR detected; short-circuiting job with success."
          exit 0
      
      - name: Environment Diagnostics (pre-setup)
        run: |
          echo "Current directory: $(pwd)"
          ls -la
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      
      - name: Environment Diagnostics (post-setup)
        run: |
          echo "Node version: $(node -v)"
          echo "npm version: $(npm -v)"
      
      - name: Install dependencies
        working-directory: ./client
        run: npm ci
      
      - name: Build production bundle
        working-directory: ./client
        run: npm run build
      
      - name: Start preview server
        working-directory: ./client
        run: |
          echo "::group::Starting preview server"
          npm run preview -- --host 127.0.0.1 --port 4173 > /tmp/preview.log 2>&1 &
          echo $! > /tmp/preview.pid
          echo "BASE_URL=http://127.0.0.1:4173" >> $GITHUB_ENV
          echo "Preview server PID: $(cat /tmp/preview.pid)"
          sleep 2
          echo "::endgroup::"
      
      - name: Wait for preview server
        run: |
          echo "Waiting for preview server to be ready..."
          for i in {1..60}; do
            if curl -fsS http://127.0.0.1:4173 >/dev/null 2>&1; then
              echo "Preview server is ready!"
              echo "Server response check:"
              curl -sS http://127.0.0.1:4173 | head -20
              break
            fi
            echo "Attempt $i/60: Server not ready yet..."
            sleep 1
          done
          if [ ! -f /tmp/preview.pid ]; then
            echo "ERROR: Preview PID file not found!"
            exit 1
          fi
          if ! ps -p $(cat /tmp/preview.pid) > /dev/null; then
            echo "ERROR: Preview server process died!"
            cat /tmp/preview.log || true
            exit 1
          fi
      
      - name: Install Playwright browsers
        working-directory: ./client
        run: npx playwright install --with-deps chromium
      
      - name: Run Playwright smoke tests
        working-directory: ./client
        env:
          BASE_URL: http://127.0.0.1:4173
        run: |
          echo "Running smoke tests against: $BASE_URL"
          npx playwright test --config=playwright-smoke.config.ts --reporter=line
      
      - name: Stop preview server
        if: always()
        run: |
          if [ -f /tmp/preview.pid ]; then
            echo "Stopping preview server..."
            kill $(cat /tmp/preview.pid) || true
            rm /tmp/preview.pid
          fi
      
      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            client/test-results/
            client/playwright-report/
          retention-days: 7
