name: Playwright Smoke Tests

on:
  pull_request:
    paths:
      - 'client/**'
      - '.github/workflows/playwright-smoke.yml'

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Environment Diagnostics
        run: |
          echo "Node version: $(node -v)"
          echo "Current directory: $(pwd)"
          ls -la
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      
      - name: Install dependencies
        working-directory: ./client
        run: npm ci
      
      - name: Build production bundle
        working-directory: ./client
        run: npm run build
      
      - name: Start preview server
        working-directory: ./client
        run: |
          echo "::group::Starting preview server"
          (npm run preview -- --host 127.0.0.1 --port 4173 & echo $! > /tmp/preview.pid) &
          echo "BASE_URL=http://127.0.0.1:4173" >> $GITHUB_ENV
          echo "Preview server PID: $(cat /tmp/preview.pid)"
          echo "::endgroup::"
      
      - name: Wait for preview server
        run: |
          echo "Waiting for preview server to be ready..."
          for i in {1..60}; do
            if curl -fsS http://127.0.0.1:4173 >/dev/null 2>&1; then
              echo "Preview server is ready!"
              break
            fi
            echo "Attempt $i/60: Server not ready yet..."
            sleep 1
          done
      
      - name: Install Playwright browsers
        working-directory: ./client
        run: npx playwright install --with-deps chromium
      
      - name: Run Playwright smoke tests
        working-directory: ./client
        env:
          BASE_URL: http://127.0.0.1:4173
        run: |
          echo "Running smoke tests against: $BASE_URL"
          npx playwright test --config=playwright-smoke.config.ts --reporter=line
      
      - name: Stop preview server
        if: always()
        run: |
          if [ -f /tmp/preview.pid ]; then
            echo "Stopping preview server..."
            kill $(cat /tmp/preview.pid) || true
            rm /tmp/preview.pid
          fi
      
      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            client/test-results/
            client/playwright-report/
          retention-days: 7